[BB-3314] Fix koa integration tests
open-craft/opencraft pull request #682
Opened 2021-01-01 07:10 UTC by shimulch

This PR fixes koa integration tests.

**JIRA tickets**: https://tasks.opencraft.com/browse/BB-3314

~~**Discussions**: ~~

**Dependencies**: https://github.com/open-craft/configuration/pull/146

~~**Screenshots**: ~~

~~**Sandbox URL**:~~

**Merge deadline**: None

~~**Testing instructions**:~~

~~**Author notes and concerns**:~~

**Reviewers**
- [ ] @0x29a
- [ ] edX reviewer[s] TBD

2021-01-05 14:23 UTC, 0x29a requested changes
Thanks for work on this, @shimulch.

I see that you targeted this PR against `koa-integration-tests`. That's my old branch which I used during planning to understand the scope of required works. You need to change target to master, since almost all changes from this branch are already there :slightly_smiling_face:

2021-01-06 11:52 UTC, shimulch commented on instance/tests/integration/factories/instance.py
> +    edx_platform_commit = '0x29a/open-release/koa.master'
@0x29a, Branch ``opencraft-release/koa.1`` created in ``open-craft/edx-platform``. I've changed references to point to that branch instead.
Also ``0x29a/open-release/koa.master`` has been deleted.

2021-01-06 11:53 UTC, shimulch commented
@0x29a I've changed target to ``master`` now. But there seems some commit's not present in the master which are not part of this PR.

2021-01-06 14:41 UTC, 0x29a commented
>But there seems some commit's not present in the master which are not part of this PR

@shimulch, changes from following commits already in master:
- https://github.com/open-craft/opencraft/pull/682/commits/3dd5f255da40ecfc5a8478b7fdbb774b69e043be
- https://github.com/open-craft/opencraft/pull/682/commits/31f74c7ab099e5d723047452d60a1271ce14e120
- https://github.com/open-craft/opencraft/pull/682/commits/64c1bb64092b423a48fbeba47d6f319bc0f2f727

I believe you can drop all my commits from this branch, and rebase the last 4 commits on top of master.

2021-01-06 18:09 UTC, shimulch commented
@0x29a, Rebased, and quashed with only my changes.

2021-01-07 08:14 UTC, merged