BB-3517 Change build success/fail email subject
open-craft/opencraft pull request #693
Opened 2021-01-14 13:53 UTC by arjunsinghy96

Changes the build success/fail email subject as requested by Ned [here](https://discuss.openedx.org/t/how-do-we-build-continuous-integration-for-the-supported-installation/3065/30?u=0x29a)

**JIRA Tickets**: BB-3517

**Discussions**: https://discuss.openedx.org/t/how-do-we-build-continuous-integration-for-the-supported-installation/3065/30?u=0x29a

**Merge deadline**: None

**Reviewers**:
- [ ] @farhaanbukhsh 
- [ ] @0x29a

2021-01-18 11:48 UTC, 0x29a commented
@arjunsinghy96, could you please sign up in Circle CI with your GitHub account and trigger pipeline for this branch?

2021-01-18 12:37 UTC, 0x29a requested changes
@arjunsinghy96, @farhaanbukhsh, I've reviewed changes and have a couple of suggestions.

First, I don't think we have to change `send_urgent_deployment_failure_email`, since we use this function only for registered user instances. They are not CI. I accidentally pointed to this function in the ticket description, sorry.

Second, with `'{} CI: Failed'.format(instance.name)` subject we'll have to change periodic build instances names to `Koa`, `Juniper`, `Ironwood` and `Master` to get desired email subject. IMO, instance with just `Master` name is a bit confusing.

Could we add two new fields to the `OpenEdXPeriodicBuildsMixin` instead? Then, we could do something like:
```python
if instance.periodic_build_success_email_subject:
    email_subject = instrance.periodic_build_success_email_subject
else:
    email_subject = 'Deployment back to normal at instance: {}'.format(instance)'
```

What do you guys think?

2021-01-18 19:04 UTC, farhaanbukhsh commented
> @arjunsinghy96, @farhaanbukhsh, I've reviewed changes and have a couple of suggestions.
> 
> First, I don't think we have to change `send_urgent_deployment_failure_email`, since we use this function only for registered user instances. They are not CI. I accidentally pointed to this function in the ticket description, sorry.

I think the function that you should be touching are https://github.com/open-craft/opencraft/blob/master/instance/models/mixins/utilities.py#L314 and https://github.com/open-craft/opencraft/blob/master/instance/models/mixins/utilities.py#L357

> 
> Second, with `'{} CI: Failed'.format(instance.name)` subject we'll have to change periodic build instances names to `Koa`, `Juniper`, `Ironwood` and `Master` to get desired email subject. IMO, instance with just `Master` name is a bit confusing.
> 
> Could we add two new fields to the `OpenEdXPeriodicBuildsMixin` instead? Then, we could do something like:
> 

What are the two fields that you are referring to?

1. periodic_build_success_email_subject
2. Name of the release? How do we avoid master is not very clear to me.

> ```python
> if instance.periodic_build_success_email_subject:
>     email_subject = instrance.periodic_build_success_email_subject
> else:
>     email_subject = 'Deployment back to normal at instance: {}'.format(instance)'
> ```
> 
> What do you guys think?

The Idea seems legit to me :+1:

2021-01-19 08:04 UTC, arjunsinghy96 commented
> First, I don't think we have to change send_urgent_deployment_failure_email, since we use this function only for registered user instances. They are not CI. I accidentally pointed to this function in the ticket description, sorry.

Are only the periodic builds considered CI? If yes, then this does make sense . I will revert changes in `send_urgent_deployment_failure_email`.

> What are the two fields that you are referring to?
 >   1. periodic_build_success_email_subject
 >   2. Name of the release? How do we avoid master is not very clear to me.

@farhaanbukhsh I think the two fields `Demid` is refering to are:
 1. periodic_build_success_email_subject
 2. periodic_build_failure_email_subject

I think instead of adding them as fields we can add them as `property` which would not require migrations. Also, adding them to `OpenEdXInstance` feels more appropriate to me as accessing `self.name` (for instance name) in `OpenEdXPeriodicBuildsMixin` might create confusion in future (accessing unrelated property. Correct me if we can do this in mixins.)

I am thinking something similar to following in `OpenEdXInstance`:

```python
@cached_property
def success_email_subject(self):
    if self.periodic_builds_enabled:
        return "{} CI: Passed".format(self.name)
   return "Deployment back to normal at instance: {}'.format(self)"

@cached_property
def failure_email_subject(self):
    if self.periodic_builds_enabled:
        return "{} CI: Failed".format(self.name)
    return "Deployment failed at instance: {}".format(self)
```
@0x29a Do we have to make the subject exactly as in [this comment](https://discuss.openedx.org/t/how-do-we-build-continuous-integration-for-the-supported-installation/3065/30)?

The subjects with above approach will be:
1. Periodic build Koa CI: Passed (or Failed)
2. Periodic build Juniper CI: Passed (or Failed)
3. Periodic build Ironwood CI: Passed (or Failed)
4. Periodic build Master CI: Passed (or Failed)

I think these satisfy the `shorten the subject and move the important information closer to the front` criteria mentioned by `Ned`

@farhaanbukhsh @0x29a What do you guys think? Does this make sense?

2021-01-19 12:37 UTC, 0x29a commented
@arjunsinghy96
>Are only the periodic builds considered CI?

Yes, correct.

>Does this make sense?

Yep, property approach looks good to me.

2021-01-19 12:43 UTC, 0x29a approved these changes
>I think these satisfy the shorten the subject and move the important information closer to the front criteria mentioned by Ned

Well, yes, you right. I just thought we could make subject to be like `Koa CI: Passed (or Failed)`, but it's not worth introducing new fields. PR looks good to me as is.

Thanks!

2021-01-19 12:48 UTC, farhaanbukhsh commented
@arjunsinghy96  can you update your PR :) thanks

2021-01-20 05:31 UTC, 0x29a commented
@nedbat, email subjects will look like: `Periodic build Koa CI: Passed (or Failed)`. Is it fine?

2021-01-20 09:06 UTC, farhaanbukhsh approved these changes
👍 

- [x] I tested this: It's a subject line change I tried comparing it with the requirement
- [x] I read through the code
~~- [ ] I checked for accessibility issues~~
~~- [ ] Includes documentation~~
~~- [ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~~

2021-01-21 12:09 UTC, nedbat commented
Looking at the code, it seems like the subject line will be "Koa CI: Passed" or "Koa CI: Failed", without the "Periodic Build" prefix. I like the way the code is: short and sweet, with the important words prominent.

2021-01-21 12:09 UTC, nedbat approved these changes

2021-01-21 13:13 UTC, arjunsinghy96 commented
_Rebased branch to master to include latest changes._

2021-01-21 16:14 UTC, merged