FAL-78 Fix the MKTG_URL_LINK_MAP override
open-craft/opencraft pull request #698
Opened 2021-01-25 19:24 UTC by s0b0lev

This PR is about resolving conflicts for the **MKTG_URL_LINK_MAP** configuration.

Authors notes:
- Included API client updates

2021-01-25 19:27 UTC, s0b0lev commented on instance/models/openedx_appserver.py
> +        'configuration_marketing_links',
Added before `configuration_extra_settings`. To support override.

2021-01-25 19:28 UTC, s0b0lev commented on instance/models/mixins/openedx_config.py
> -                "MKTG_URL_LINK_MAP": {
Completly removed from `EDXAPP_LMS_ENV_EXTRA`. 

MKTG_URL_LINK_MAP - will contain a list of only disabled pages.

2021-01-25 21:53 UTC, nizarmah commented
@s0b0lev 

> Instead of injecting the full list into MKTG_URL_LINK_MAP - this code will add only disabled pages

https://github.com/edx/edx-platform/blob/70cc6d860814a8447b95d223066d4ada0b1c70bc/common/djangoapps/edxmako/shortcuts.py#L48-L59

The variables mentioned above indicate that it should be allowed to not just disable certain marketting links, but also override them.

Accordingly, this seems to be eliminating functionality. 

Would you mind, please, changing the approach you took in order to resolve the issue? 

cc @lgp171188 I'd like to hear your thoughts on this please

2021-01-25 21:56 UTC, nizarmah requested changes
@s0b0lev 

> Instead of injecting the full list into MKTG_URL_LINK_MAP - this code will add only disabled pages

https://github.com/edx/edx-platform/blob/70cc6d860814a8447b95d223066d4ada0b1c70bc/common/djangoapps/edxmako/shortcuts.py#L48-L59

The variables mentioned above indicate that it should be allowed to not just disable certain marketting links, but also override them.

Accordingly, based on your description this seems to be eliminating functionality. 

Would you mind, please, changing the approach you took in order to resolve the issue? 

cc @lgp171188 I'd like to hear your thoughts on this please

2021-02-07 22:44 UTC, nizarmah reviewed
:+1:

- [ ] I tested this:
  - [x] I provisioned a new instance and verified that customization using the extra configuration were not affected.
  - [x] I verified that Studio does not crash in newly provisioned instances
  - [ ] I disabled the pages from the frontend app and made sure the changes got reflected
- [x] I read through the code
- [x] I checked for accessibility issues
- [ ] ~~Includes documentation~~
- [ ] ~~I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~~

---

@s0b0lev I had trouble testing the third point, I mentioned earlier, on my machine and on Ocim stage. Can you please find someone who would be able to review that last bullet point?

2021-02-11 23:44 UTC, nizarmah approved these changes
@s0b0lev thanks for creating the sandbox instance for me to test it! I really appreciate it! 

👍🏼 

- [x] I tested this:
  - [x] I provisioned a new instance and verified that customization using the extra configuration were not affected.
  - [x] I verified that Studio does not crash in newly provisioned instances
  - [x] I disabled the pages from the frontend app and made sure the changes got reflected

2021-03-21 07:26 UTC, merged