[WIP]: BB-3616 Add check for DNS configuration
open-craft/opencraft pull request #704
Opened 2021-02-03 12:36 UTC by arjunsinghy96

If external domain is added to the instance, we need to check that proper CNAME records are created with the DNS by use.

**Related Tickets**: BB-3616

**Author Notes**
I will update the description before moving the PR out of WIP

2021-02-04 12:46 UTC, farhaanbukhsh requested changes
I have few suggestions but overall the approach LGTM :+1:

2021-02-04 12:46 UTC, farhaanbukhsh commented on registration/utils.py
> +        return False
we should not let the error pass silently, we should log this. Else we will never know if the records were not configured properly or any other exception occured.

2021-02-04 12:46 UTC, farhaanbukhsh commented on registration/utils.py
> +import dns.resolver
can we make this as 
```suggestion
import dns.resolver as dns_resolver
```

2021-02-04 13:02 UTC, farhaanbukhsh commented on registration/utils.py
> +            record == 'haproxy.opencraft.hosting'
we should get  `haproxy.opencraft.hosting` from a constant since this can change, we might as well use another load ballencer.

2021-02-08 21:31 UTC, kaizoku approved these changes
@arjunsinghy96 :+1:

Thanks for the updated test instructions.
I have two very small nits but it's otherwise working for me.

2021-02-10 12:41 UTC, farhaanbukhsh approved these changes

2021-02-10 12:43 UTC, merged