BB-3870 Add ThemeNavigationPage for newConsole
open-craft/opencraft pull request #747
Opened 2021-03-22 13:12 UTC by arjunsinghy96

Adds new ThemeNavigationPage for newConsole and
move the Color Picker components to the sidebar

**JIRA Tickets** [BB-3870](https://tasks.opencraft.com/browse/BB-3870) [Gitlab#722](https://gitlab.com/opencraft/dev/opencraft/-/issues/722)

**Testing Instructions**
1. Checkout to this branch
2. Run OCIM frontend and backend dev servers.
3. Make sure that a test instance is created in OCIM admin.
4. Visit http://localhost:3000/newconsole/theming/navigation/edit
5. Make sure that all the elements are present in Sidebar.
6. Verify that changing `ColorInputField` values changes the theme data in `BetaTestApplication`

**Screenshot**
![navigation-theme](https://user-images.githubusercontent.com/18226212/111994811-35b1a580-8b3e-11eb-85a9-7dc7272d6b47.png)

2021-03-28 01:20 UTC, farhaanbukhsh requested changes
I have added few nits but over all this looks ready to merge

2021-03-28 01:20 UTC, farhaanbukhsh commented on frontend/src/routes/console.tsx
> +      />
We need to remove the old theme navigation here.

2021-04-05 12:13 UTC, farhaanbukhsh commented
@arjunsinghy96 can you please resolve the conflict and rebase this PR

2021-04-05 15:16 UTC, farhaanbukhsh approved these changes
👍 

- [x] I tested this: I ran this on my local devstack and checked different flows
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~
- [ ] ~~Includes documentation~~
- [ ] ~~I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~~

2021-04-05 16:44 UTC, arjunsinghy96 commented
The `integration test` CI is failing and its not related to work done in this PR .

2021-04-05 16:47 UTC, merged