Update installation docs
open-craft/opencraft pull request #882
Opened 2022-03-09 08:32 UTC by karimelghazouly

2022-03-09 08:56 UTC, saksham115 requested changes
@karimelghazouly please update the PR description correctly

2022-03-09 08:56 UTC, saksham115 commented on documentation/installation.md
> +Also you can docker for development and the steps are mentioned [here|https://ocim.opencraft.com/en/latest/development/docker/]
you can use the*

2022-03-10 14:43 UTC, saksham115 approved these changes
👍🏻 

- [ ]  I tested this: Nothing to test. Documentation changes.
- [ ]  I read through the code

2022-04-11 11:21 UTC, 0x29a commented
This PR is no longer relevant. See the changes for https://github.com/open-craft/opencraft/pull/892.

2022-04-11 11:21 UTC, closed without merging